type = 1; % 0: normal, 1: legacy to generate identical results compared to C code v1.1

%NOTE: use gcc 4.7.4 with Matlab 2015b

if (type == 0)

    mex -v -largeArrayDims CXXOPTIMFLAGS="-O3 -DNDEBUG" LDOPTIMFLAGS="-O2" -DUSE_OpenMP CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" ...
                                -I../Source -cxx -c ...
                                ../Source/DistanceFunctions/EuclideanFunction.cpp ...
                                ../Source/DistanceFunctions/NormalizedEuclideanFunction.cpp ...
                                ../Source/DistanceFunctions/StdWeightedEuclideanFunction.cpp ...
                                ../Source/DistanceFunctions/OverlapFunction.cpp ...
                                ../Source/DistanceFunctions/VDMFunction.cpp ...
                                ../Source/Date.cpp ...
                                ../Source/DateContainer.cpp ...
                                ../Source/StringTokenizer.cpp ...
                                ../Source/Utils.cpp ...
                                ../Source/Matrix.cpp ...
                                ../Source/Dataset.cpp ...
                                ../Source/ExtendedDataset.cpp ...
                                ../Source/ComplexityMeasures.cpp ...
                                ../Source/Statistics.cpp ...
                                ../Source/SMO.cpp ...
                                ../Source/InputOptions.cpp ...
                                DCoL.cpp


    mex -v -largeArrayDims CXXOPTIMFLAGS="-O3 -DNDEBUG" LDOPTIMFLAGS="-O2" -DUSE_OpenMP CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" ...
                                -cxx DCoL.o ...
                                EuclideanFunction.o ...
                                NormalizedEuclideanFunction.o ...
                                StdWeightedEuclideanFunction.o ...
                                OverlapFunction.o ...
                                VDMFunction.o ...
                                Date.o ...
                                DateContainer.o ...
                                StringTokenizer.o ...
                                Utils.o ...
                                Matrix.o ...
                                Dataset.o ...
                                ExtendedDataset.o ...
                                ComplexityMeasures.o ...
                                Statistics.o ...
                                SMO.o ...
                                InputOptions.o
                            
else
    fprintf('build ori results version\n');
    mex -v -largeArrayDims CXXOPTIMFLAGS="-O3 -DNDEBUG" LDOPTIMFLAGS="-O2" -DUSE_OpenMP CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" ...
                                -I../Source -cxx -c ...
                                ../Source/DistanceFunctions/EuclideanFunction.cpp ...
                                ../Source/DistanceFunctions/NormalizedEuclideanFunction.cpp ...
                                ../Source/DistanceFunctions/StdWeightedEuclideanFunction.cpp ...
                                ../Source/DistanceFunctions/OverlapFunction.cpp ...
                                ../Source/DistanceFunctions/VDMFunction.cpp ...
                                ../Source/Date.cpp ...
                                ../Source/DateContainer.cpp ...
                                ../Source/StringTokenizer.cpp ...
                                ../Source/Utils.cpp ...
                                ../Source/Matrix.cpp ...
                                ../Source/Dataset.cpp ...
                                ../Source/ExtendedDataset.cpp ...
                                ../Source/ComplexityMeasures.cpp ...
                                ../Source/Statistics.cpp ...
                                ../Source/SMO.cpp ...
                                ../Source/InputOptions.cpp ...
                                DCoL_ori.cpp


    mex -v -largeArrayDims CXXOPTIMFLAGS="-O3 -DNDEBUG" LDOPTIMFLAGS="-O2" -DUSE_OpenMP CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" ...
                                -cxx DCoL_ori.o ...
                                EuclideanFunction.o ...
                                NormalizedEuclideanFunction.o ...
                                StdWeightedEuclideanFunction.o ...
                                OverlapFunction.o ...
                                VDMFunction.o ...
                                Date.o ...
                                DateContainer.o ...
                                StringTokenizer.o ...
                                Utils.o ...
                                Matrix.o ...
                                Dataset.o ...
                                ExtendedDataset.o ...
                                ComplexityMeasures.o ...
                                Statistics.o ...
                                SMO.o ...
                                InputOptions.o
end
                                                                
