type = 2; % 0: normal, 1: legacy to generate identical results compared to C code v1.1, 2: all

%module load gcc/4.8.0 matlab/R2013a
%matlab -nojvm < build_mcc.m 

if (type == 0 || type == 2)

    mex -v -largeArrayDims CXXOPTIMFLAGS="-O3 -DNDEBUG" LDOPTIMFLAGS="-O2" CXXFLAGS="\$CXXFLAGS -std=c++11" ...
                                -I../Source -cxx -c ...
                                ../Source/DistanceFunctions/EuclideanFunction.cpp ...
                                ../Source/DistanceFunctions/NormalizedEuclideanFunction.cpp ...
                                ../Source/DistanceFunctions/StdWeightedEuclideanFunction.cpp ...
                                ../Source/DistanceFunctions/OverlapFunction.cpp ...
                                ../Source/DistanceFunctions/VDMFunction.cpp ...
                                ../Source/Date.cpp ...
                                ../Source/DateContainer.cpp ...
                                ../Source/StringTokenizer.cpp ...
                                ../Source/Utils.cpp ...
                                ../Source/Matrix.cpp ...
                                ../Source/Dataset.cpp ...
                                ../Source/ExtendedDataset.cpp ...
                                ../Source/ComplexityMeasures.cpp ...
                                ../Source/Statistics.cpp ...
                                ../Source/SMO.cpp ...
                                ../Source/InputOptions.cpp ...
                                dcol.cpp


    mex -v -largeArrayDims CXXOPTIMFLAGS="-O3 -DNDEBUG" LDOPTIMFLAGS="-O2" ...
                                -cxx dcol.o ...
                                EuclideanFunction.o ...
                                NormalizedEuclideanFunction.o ...
                                StdWeightedEuclideanFunction.o ...
                                OverlapFunction.o ...
                                VDMFunction.o ...
                                Date.o ...
                                DateContainer.o ...
                                StringTokenizer.o ...
                                Utils.o ...
                                Matrix.o ...
                                Dataset.o ...
                                ExtendedDataset.o ...
                                ComplexityMeasures.o ...
                                Statistics.o ...
                                SMO.o ...
                                InputOptions.o
                            
end

if(type == 1 || type == 2)

    fprintf('build ori results version\n');
    mex -v -largeArrayDims CXXOPTIMFLAGS="-O3 -DNDEBUG" LDOPTIMFLAGS="-O2" CXXFLAGS="\$CXXFLAGS -std=c++11" ...
                                -I../Source -cxx -c ...
                                ../Source/DistanceFunctions/EuclideanFunction.cpp ...
                                ../Source/DistanceFunctions/NormalizedEuclideanFunction.cpp ...
                                ../Source/DistanceFunctions/StdWeightedEuclideanFunction.cpp ...
                                ../Source/DistanceFunctions/OverlapFunction.cpp ...
                                ../Source/DistanceFunctions/VDMFunction.cpp ...
                                ../Source/Date.cpp ...
                                ../Source/DateContainer.cpp ...
                                ../Source/StringTokenizer.cpp ...
                                ../Source/Utils.cpp ...
                                ../Source/Matrix.cpp ...
                                ../Source/Dataset.cpp ...
                                ../Source/ExtendedDataset.cpp ...
                                ../Source/ComplexityMeasures.cpp ...
                                ../Source/Statistics.cpp ...
                                ../Source/SMO.cpp ...
                                ../Source/InputOptions.cpp ...
                                dcol_ori.cpp


    mex -v -largeArrayDims CXXOPTIMFLAGS="-O3 -DNDEBUG" LDOPTIMFLAGS="-O2" ...
                                -cxx dcol_ori.o ...
                                EuclideanFunction.o ...
                                NormalizedEuclideanFunction.o ...
                                StdWeightedEuclideanFunction.o ...
                                OverlapFunction.o ...
                                VDMFunction.o ...
                                Date.o ...
                                DateContainer.o ...
                                StringTokenizer.o ...
                                Utils.o ...
                                Matrix.o ...
                                Dataset.o ...
                                ExtendedDataset.o ...
                                ComplexityMeasures.o ...
                                Statistics.o ...
                                SMO.o ...
                                InputOptions.o
end
                                                                
